<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
	<PropertyGroup>
		<Authors>daemitus, croizat</Authors>
		<Version>0.0.0.0</Version>
		<LangVersion>preview</LangVersion>
		<LocalCS>false</LocalCS>
	</PropertyGroup>

	<PropertyGroup Condition="'$(LocalCS)'=='true'">
		<DefineConstants>LOCAL_CS</DefineConstants>
		<Use_Dalamud_FFXIVClientStructs>false</Use_Dalamud_FFXIVClientStructs>
	</PropertyGroup>

	<ItemGroup Condition="'$(LocalCS)'=='true'">
		<ProjectReference Include="..\..\..\FFXIVClientStructs\FFXIVClientStructs\FFXIVClientStructs.csproj" Private="true" />
		<ProjectReference Include="..\..\..\FFXIVClientStructs\InteropGenerator.Runtime\InteropGenerator.Runtime.csproj" Private="true" />
		<ProjectReference Include="..\..\..\FFXIVClientStructs\InteropGenerator\InteropGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="croizat.clib" Version="1.0.94" />
	  <PackageReference Include="ECommons" Version="3.2.0.19" />
	</ItemGroup>
</Project>
